{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-cast-ingress
  labels:
    app: movie-cast-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Remplacez par l'issuer approprié
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - app.devops-emi.cloudns.ch
    secretName: app-tls-secret # Nom du secret où sera stocké le certificat
  rules:
    - host: "app.devops-emi.cloudns.ch"
      http:
        paths:
          - path: /api/v1/movies
            pathType: Prefix
            backend:
              service:
                name: movie-service
                port:
                  number: 8002
          - path: /api/v1/casts
            pathType: Prefix
            backend:
              service:
                name: cast-service
                port:
                  number: 8001
{{- end }}