{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-cast-ingress
  labels:
    app: movie-cast-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: "app.devops-emi.cloudns.ch"
      http:
        paths:
          - path: /api/v1/movies
            pathType: Prefix
            backend:
              service:
                name: movie-service
                port:
                  number: 8002
          - path: /api/v1/casts
            pathType: Prefix
            backend:
              service:
                name: cast-service
                port:
                  number: 8001
    - host: "argocd.devops-emi.cloudns.ch"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
{{- end }}
