{{- range $service := (list "movieService" "castService") }}
{{- $serviceValues := index $.Values $service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceValues.name }}
  labels:
    app: {{ $serviceValues.name }}
spec:
  type: {{ $serviceValues.service.type }}
  ports:
    - port: {{ $serviceValues.service.port }}
      targetPort: {{ $serviceValues.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ $serviceValues.name }}
---
{{- end }}