# Default values for movie-cast-services.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

movieService:
  name: movie-service
  replicaCount: 1
  image:
    repository: newemira/movie-service
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 8002
    targetPort: 8000
  database:
    name: movie_db_dev
    username: movie_db_username
    password: movie_db_password

castService:
  name: cast-service
  replicaCount: 1
  image:
    repository: newemira/cast-service
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 8001
    targetPort: 8000
  database:
    name: cast_db_dev
    username: cast_db_username
    password: cast_db_password

postgresql:
  enabled: true
  architecture: standalone
  auth:
    enablePostgresUser: true
    postgresPassword: "postgres"
    database: movie_db_dev

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: dev-strip-prefix@kubernetescrd
  hosts:
    - host: app.devops-emi.cloudns.ch
      paths:
        - path: /api/v1/movies
          pathType: Prefix
          service: movie-service
          port: 8002
        - path: /api/v1/casts
          pathType: Prefix
          service: cast-service
          port: 8001