FROM python:3.8-slim

# Définir le chemin Python avant de copier l'application
ENV PYTHONPATH=/app

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN apt-get update \
    && apt-get install gcc -y \
    && apt-get clean

RUN pip install -r /app/requirements.txt \
    && rm -rf /root/.cache/pip

COPY . /app/