apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  labels:
    app: movie-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
        tier: backend
    spec:
      containers:
        - name: movie-service
          image: newemira/movie-service:latest
          env:
            - name: DATABASE_URI
              value: postgresql://movie_db_username:movie_db_password@movie-db-service/movie_db_dev
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: movie-service-volume
              mountPath: /data/
      volumes:
        - name: movie-service-volume
          persistentVolumeClaim:
            claimName: movie-service-pvc