apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-db-config
data:
   postgresql.conf: |
    # Configuration PostgreSQL personnalisée
    max_connections = 100
    shared_buffers = 128MB
    log_timezone = 'UTC'
    hba_file = '/etc/postgresql/pg_hba.conf'
    config_file = '/etc/postgresql/postgresql.conf'
   pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    host    all             all             0.0.0.0/0               trust
 