apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service 
  labels:
    app: movie-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - args:
            - uvicorn
            - movie.app.main:app
            - --reload
            - --host
            - 0.0.0.0
            - --port
            - "8000"
          env:
            - name: CAST_SERVICE_HOST_URL
              value: http://cast_service:8000/api/v1/casts/
            - name: DATABASE_URI
              value: postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
          image: newemira/movie-service:latest
          name: movie-service
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /app/
              name: movie-service-pv
      restartPolicy: Always
      volumes:
        - name: movie-service-pv
          persistentVolumeClaim:
            claimName: movie-service-pvc
